[versions]
groovy = "4.0.29"
spock = "2.3-groovy-4.0"
byte-buddy = "1.18.1"
java = "24"
jackson = '2.20.1'

[libraries]
groovy-bom = { group = "org.apache.groovy", name = "groovy-bom", version.ref = "groovy" }
spock-bom = { group = "org.spockframework", name = "spock-bom", version.ref = "spock" }
byte-buddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byte-buddy" }
jackson-bom = { group = 'com.fasterxml.jackson', name = 'jackson-bom', version.ref = 'jackson' }
